version: '2'
services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
    image: ryannhg/angular
    ports:
      - "8000:8000"
    volumes:
      #- ./index.js:/usr/src/app/index.js
      - ./steerhigh-webapp/src/app:/usr/src/app/app
